apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
commonLabels:
  env: dev
nameSuffix: -dev
configMapGenerator:
- name: spring-petclinic
  env: ./dev-environment
patchesStrategicMerge:
- change-cause.yaml
