apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
commonLabels:
  env: staging
nameSuffix: -staging
configMapGenerator:
- name: spring-petclinic
  env: ./staging-environment
patches:
- change-cause.yaml
